apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: payment-webhook
  name: payment-webhook
spec:
  ports:
  - name: "3000"
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: payment-ms
  type: NodePort
status:
  loadBalancer: {}